CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "GameTable" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "AppId" integer NOT NULL,
    CONSTRAINT "PK_GameTable" PRIMARY KEY ("Id")
);

CREATE TABLE "MetricTable" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GameId" integer NOT NULL,
    "PlayerCount" integer NOT NULL,
    "Price" numeric NOT NULL,
    "DiscountPercent" integer NOT NULL,
    "PositiveReviews" integer NOT NULL,
    "NegativeReviews" integer NOT NULL,
    "ReviewScoreLabel" text,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MetricTable" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MetricTable_GameTable_GameId" FOREIGN KEY ("GameId") REFERENCES "GameTable" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MetricTable_GameId" ON "MetricTable" ("GameId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251218010729_InitialCreate', '10.0.0');

COMMIT;

START TRANSACTION;
CREATE TABLE "ReviewTable" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GameId" integer NOT NULL,
    "RecommendationId" text NOT NULL,
    "ReviewText" text NOT NULL,
    "Language" text NOT NULL,
    "VotedUp" boolean NOT NULL,
    "TimestampCreated" timestamp with time zone NOT NULL,
    "TimestampUpdated" timestamp with time zone NOT NULL,
    "WeightedVoteScore" double precision NOT NULL,
    "VotesUp" integer NOT NULL,
    "VotesFunny" integer NOT NULL,
    "CommentCount" integer NOT NULL,
    "SteamPurchase" boolean NOT NULL,
    "ReceivedForFree" boolean NOT NULL,
    "WrittenDuringEarlyAccess" boolean NOT NULL,
    "PrimarilySteamDeck" boolean NOT NULL,
    "ChangedVote" boolean NOT NULL,
    "AuthorSteamId" text NOT NULL,
    "AuthorNumGamesOwned" integer NOT NULL,
    "AuthorNumReviews" integer NOT NULL,
    "AuthorPlaytimeForever" integer NOT NULL,
    "AuthorPlaytimeLastTwoWeeks" integer NOT NULL,
    "AuthorPlaytimeAtReview" integer NOT NULL,
    "AuthorLastPlayed" timestamp with time zone NOT NULL,
    "UpdatedCount" integer NOT NULL,
    CONSTRAINT "PK_ReviewTable" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReviewTable_GameTable_GameId" FOREIGN KEY ("GameId") REFERENCES "GameTable" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ReviewTable_GameId" ON "ReviewTable" ("GameId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251228192640_AddReviewTable', '10.0.0');

COMMIT;

START TRANSACTION;
CREATE UNIQUE INDEX "IX_GameTable_AppId" ON "GameTable" ("AppId");

CREATE INDEX "IX_MetricTable_GameId_Timestamp" ON "MetricTable" ("GameId", "Timestamp");

CREATE UNIQUE INDEX "IX_ReviewTable_RecommendationId" ON "ReviewTable" ("RecommendationId");

CREATE INDEX "IX_ReviewTable_GameId_TimestampCreated" ON "ReviewTable" ("GameId", "TimestampCreated");

CREATE INDEX "IX_ReviewTable_Language" ON "ReviewTable" ("Language");

CREATE INDEX "IX_ReviewTable_VotedUp" ON "ReviewTable" ("VotedUp");

CREATE INDEX "IX_ReviewTable_AuthorSteamId" ON "ReviewTable" ("AuthorSteamId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260101000000_AddIndexes', '10.0.0');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_ReviewTable_GameId";

DROP INDEX "IX_MetricTable_GameId";

ALTER TABLE "GameTable" ADD "Developer" text NOT NULL DEFAULT '';

ALTER TABLE "GameTable" ADD "Genre" text NOT NULL DEFAULT '';

ALTER TABLE "GameTable" ADD "HeaderImageUrl" text NOT NULL DEFAULT '';

ALTER TABLE "GameTable" ADD "Publisher" text NOT NULL DEFAULT '';

ALTER TABLE "GameTable" ADD "ReleaseDate" text NOT NULL DEFAULT '';

ALTER TABLE "GameTable" ADD "Tags" jsonb NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260422153905_AddGameTags', '10.0.0');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260422163820_AddGameData', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "GameTable" ALTER COLUMN "Tags" DROP NOT NULL;

ALTER TABLE "GameTable" ALTER COLUMN "ReleaseDate" DROP NOT NULL;

ALTER TABLE "GameTable" ALTER COLUMN "Publisher" DROP NOT NULL;

ALTER TABLE "GameTable" ALTER COLUMN "HeaderImageUrl" DROP NOT NULL;

ALTER TABLE "GameTable" ALTER COLUMN "Genre" DROP NOT NULL;

ALTER TABLE "GameTable" ALTER COLUMN "Developer" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260422202715_UpdateSchema', '10.0.0');

COMMIT;

