// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SteamHeartAPI.Data;

#nullable disable

namespace SteamHeartAPI.Migrations
{
    [DbContext(typeof(SteamHeartContext))]
    partial class SteamHeartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SteamHeartAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, int>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.ToTable("GameTable");
                });

            modelBuilder.Entity("SteamHeartAPI.Models.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("NegativeReviews")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<int>("PositiveReviews")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ReviewScoreLabel")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Timestamp");

                    b.ToTable("MetricTable");
                });

            modelBuilder.Entity("SteamHeartAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuthorLastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AuthorNumGamesOwned")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorNumReviews")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorPlaytimeAtReview")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorPlaytimeForever")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorPlaytimeLastTwoWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("AuthorSteamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ChangedVote")
                        .HasColumnType("boolean");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrimarilySteamDeck")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceivedForFree")
                        .HasColumnType("boolean");

                    b.Property<string>("RecommendationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SteamPurchase")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimestampUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("VotedUp")
                        .HasColumnType("boolean");

                    b.Property<int>("VotesFunny")
                        .HasColumnType("integer");

                    b.Property<int>("VotesUp")
                        .HasColumnType("integer");

                    b.Property<double>("WeightedVoteScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("WrittenDuringEarlyAccess")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AuthorSteamId");

                    b.HasIndex("Language");

                    b.HasIndex("RecommendationId")
                        .IsUnique();

                    b.HasIndex("VotedUp");

                    b.HasIndex("GameId", "TimestampCreated");

                    b.ToTable("ReviewTable");
                });

            modelBuilder.Entity("SteamHeartAPI.Models.Metric", b =>
                {
                    b.HasOne("SteamHeartAPI.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamHeartAPI.Models.Review", b =>
                {
                    b.HasOne("SteamHeartAPI.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
